name: date_kit
description: A Dart package to handle all the possible 
version: 1.0.0
repository: https://github.com/danishkumar63/date_kit

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  intl: ^0.17.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0