name: date_kit
description: A comprehensive Dart package for DateTime operations, with a rich set of functions and extensions for seamless manipulation and formatting.
version: 1.0.3
repository: https://github.com/danishkumar63/date_kit
issue_tracker: https://github.com/danishkumar63/date_kit/issues

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  intl: ^0.20.2

dev_dependencies:
  lints: ^5.1.1
  test: ^1.21.0